site_name: Documentation personnel
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
navigation_depth: -1
nav:
  - Symfony:
    - Form: 
      - Text Fields:
        - TextType : Symfony/Form/TextFields/texttype.md
        - TextareaType : Symfony/Form/TextFields/textareatype.md
        - EmailType : Symfony/Form/TextFields/emailtype.md
        - IntegerType : Symfony/Form/TextFields/integertype.md
        - MoneyType : Symfony/Form/TextFields/moneytype.md
        - NumberType : Symfony/Form/TextFields/numbertype.md
        - PasswordType : Symfony/Form/TextFields/passwordtype.md
        - PercentType : Symfony/Form/TextFields/percenttype.md
        - SearchType : Symfony/Form/TextFields/searchtype.md
        - UrlType : Symfony/Form/TextFields/urltype.md
        - RangeType : Symfony/Form/TextFields/rangetype.md
        - TelType : Symfony/Form/TextFields/teltype.md
        - ColorType : Symfony/Form/TextFields/colortype.md
      - Choice Fields :
        - ChoiceType : void.md
        - EnumType : void.md
        - EntityType : void.md
        - CountryType : void.md
        - LanguageType : void.md
        - LocaleType : void.md
        - TimezoneType : void.md
        - CurrencyType : void.md
      - Date and Time Fields :
        - DateType : void.md
        - DateIntervalType : void.md
        - DateTimeType : void.md
        - TimeType : void.md
        - BirthdayType : void.md
        - WeekType : void.md
      - Other Fields :
        - CheckboxType : void.md
        - FileType : void.md
        - RadioType : void.md
  - ORMC:
    - PES_Aller:
      - Depense: void.md
      - Recette: ORMC/PES_Aller/Recette/recette.md
      - Facture: void.md
      - Marche: void.md
      - PJ: void.md
    - PES_Retour: 
      - Depense: void.md
      - Recette: void.md
      - Client: void.md
    - Budgétaire: void.md
